# Generated by Django 6.0.4 on 2026-04-09 22:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('domicilio', models.CharField(max_length=255)),
            ],
        ),
    ]
